channels:
- conda-forge
dependencies:
- python=3.11.9
- pip
- pip:
  - mlflow<3,>=2.3
  - cloudpickle==2.2.1
  - numpy==1.24.3
  - psutil==7.0.0
  - scikit-learn==1.2.2
  - scipy==1.15.3
name: mlflow-env
