model:
  name: house_price_model
  target_variable: price
  best_model: RandomForest
  parameters:
    n_estimators: 100
    max_depth: 10
    min_samples_split: 5
    min_samples_leaf: 2
    random_state: 42